### ISSUE TITLE
Request to access Visage dataset

### ISSUE THREAD

**Issue by sxs4337** [4ND4/Vec2UAge#1]
Hi.
I am interested in using the Visage dataset. I had filled up the form on the website few weeks back. Can you kindly provide access to the visage dataset? Will truly appreciate it.

Thanks!

**Comment by 4ND4** [comment]
Hi sxs4337,

I'm afraid I'm not in charge of the distribution of the dataset. The request can only be done through the [form](https://www.forensicsandsecurity.com/visage) which is revised by the relevant authorities.

Kind Regards,

**Comment by sxs4337** [comment]
Thanks.
